Add refund cron
adahandle/adahandle-express pull request #54
Opened 2022-01-13 04:51 UTC by guavajellyaaron

2022-01-13 15:23 UTC, cjkoepke requested changes
This looks really great, there is just some optimization/clarity on some things I'd like to go over. Let me know if a call would help to expound on some of them.

2022-01-13 20:24 UTC, guavajellyaaron commented on src/express/handlers/jobs/refunds/getRefundWallet.test.ts
> +    it('Should send lock the cron and send notification if there is not enough data', async () => {
copy pasta... nice catch!

2022-01-13 20:26 UTC, guavajellyaaron commented on src/express/handlers/jobs/refunds/getRefundWallet.ts
> +    const refundWallet = await getMintWalletServer();
I agree with this as well. I might change this completely to just check the balance

2022-01-13 20:27 UTC, guavajellyaaron commented on src/express/handlers/jobs/refunds/index.ts
> +            return verifiedRefund;
Because we have to await the results

2022-01-13 20:32 UTC, guavajellyaaron commented on src/express/handlers/jobs/refunds/verifyRefund.ts
> +        results = await lookupTransaction(address);
I agree. We were discussing adding it here: https://github.com/adahandle/adahandle-express/pull/54/files/c9c18c6f39a14788ecd0d9a05d91252238c48574#diff-167f87039e87f98f27cce9bccd9b79b81e4d01f746c2694835f4138d963a7d95R20. Do you think this would be wise to add? We werent sure why we would need it after the transaction was submitted since we would find it onchain.

2022-01-13 22:37 UTC, cjkoepke commented on src/express/handlers/jobs/refunds/index.ts
> +        await awaitForEach(verifiedRefunds, (refund) => processRefund(refund, refundWallet));
The amount of payments depends on the max transaction size allowed by Cardano. This is handled internally when the transaction is serialized into a string and then submitted to the wallet node. I'm not sure the exact amount of payments to size ratio, but I'm thinking it's something around 400-500.

The best way to test is to serialize a payment and determine the max inputs/outputs that will fit before exceeding the total size (currently at 16,384 bytes).

2022-01-13 22:39 UTC, cjkoepke commented on src/express/handlers/jobs/refunds/verifyRefund.ts
> +        results = await lookupTransaction(address);
Definitely add it there, since when you look up the refund later you can get the transaction by the ID and return the outputs. If the refund is accurate and in one of those outputs, then it is confirmed by extension of the fact that the transaction ID exists and is confirmed itself.

2022-01-14 01:07 UTC, guavajellyaaron commented on src/express/handlers/jobs/refunds/index.ts
> +        await awaitForEach(verifiedRefunds, (refund) => processRefund(refund, refundWallet));
Sounds good. I'm going to dig in but I'm curious if a "payment" the return addresses and amounts?

2022-01-14 05:34 UTC, happygaijin approved these changes
LGTM

2022-01-14 05:35 UTC, merged

2022-01-14 16:48 UTC, cjkoepke commented on src/express/handlers/jobs/refunds/index.ts
> +        await awaitForEach(verifiedRefunds, (refund) => processRefund(refund, refundWallet));
In this particular method from the library, a "payment" is a transaction. That's why you can add multiple address/amount values into the array.